### ISSUE TITLE
decoding invalid JSON starting with number and followed by extra characters doesn't throw exception

### ISSUE THREAD

**Issue by bsuh** [sile/jsone#68]
This is on version 1.5.6 as well as master branch.

```
~/git/jsone % make start
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling jsone
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling jsone
Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] [dtrace]

Eshell V12.1.2  (abort with ^G)
1> ===> Booted jsone

1> jsone:decode(<<"1@">>).
1
2> jsone:decode(<<"1@s">>).
1
```

**Comment by sile** [comment]
Thank you for reporting this issue.
This is because the current implementation of `jsone:decode/1` just discards the remaining (unconsumed) binary [in this line](https://github.com/sile/jsone/blob/master/src/jsone.erl#L337).
It feels better to raise an error if the remaining binary size is not empty (maybe it's worth allowing binaries that only contain whitespace characters though).

**Comment by bsuh** [comment]
Allowing whitespace after seems reasonable. JavaScript API `JSON.parse()` allows whitespace after (but not garbage characters).

```
>> JSON.parse(" 1")
1
>> JSON.parse(" 1 ")
1
```

**Comment by sile** [comment]
Thank you for your information!
I'll implement this check this or next week (however, if you're interested in doing that, the contribution is very welcomed).

**Comment by sile** [comment]
FYI: Created PR #69
